version: '3.7'

services:
  server:
    build:
      context: ./server/
    command: /usr/app/node_modules/.bin/nodemon app.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
